Online_School_Teacher/Online_School_Teacher/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Online_School_Teacher.Models;

namespace Online_School_Teacher.Controllers
{
    public class StudentsController : Controller
    {
        private readonly DatabaseContext _context;

        public StudentsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Email,Name,Password,ConfrimPassword,JWT_Token")] Student student)
        {

            if (ModelState.IsValid)
            {
                student.JWT_Token = GenerateToken(student.Email);
                _context.Add(student);
                await _context.SaveChangesAsync();
                ViewBag.Message = "Registration Complete!";
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Please Provide Valid Information");
            }
            return View(student);
        }

        [AcceptVerbs("Get", "Post")]
        
        public async Task<IActionResult> StudentExists(String email)
        {
            var data = await _context.Student.Where(x => x.Email == email).FirstOrDefaultAsync<Student>();

            if (data == null)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        private static string GenerateToken(String Email)
        {
            var securityKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Constent.Secret));
            var credentials = new SigningCredentials(securityKey, SecurityAlgorithms.HmacSha256);

            var secToken = new JwtSecurityToken(
                signingCredentials: credentials,
                issuer: Constent.Issuer,
                audience: Constent.Audiance,
                claims: new[]
                {
                new Claim(JwtRegisteredClaimNames.Sub, Email),
                new Claim(ClaimTypes.Role, "Student")
                },
                notBefore: DateTime.Now);
               /// expires: DateTime.UtcNow.AddMonths(2));

            var handler = new JwtSecurityTokenHandler();
            
            return handler.WriteToken(secToken);
        }

        /*
                Constants.Issuer,
                Constants.Audiance,
                claims,
                notBefore: DateTime.Now,
                expires: DateTime.Now.AddDays(1),
                signingCredentials);
         
       */






    }
}

Online_School_Teacher/Online_School_Teacher/Controllers/TeachersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Online_School_Teacher.Models;

namespace Online_School_Teacher.Controllers
{
    [Authorize(Roles = "Teacher", AuthenticationSchemes = "Teacher")]
    public class TeachersController : Controller
    {
        private readonly DatabaseContext _context;

        public TeachersController(DatabaseContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }


        [AllowAnonymous]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create([Bind("Email", "Name", "Password", "JWT_Token", "ConfrimPassword")]Teacher teacher)
        {

            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                ViewBag.Message = "Registration Complete!";
            }
            return View(teacher);

        }
        [AcceptVerbs("Get", "Post")]
        public async Task<IActionResult> UniqueEmail(String email)
        {
            var data = await _context.Teacher.Where(x => x.Email == email).FirstOrDefaultAsync<Teacher>();

            if (data == null)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        private bool TeacherExists(string id)
        {
            return _context.Teacher.Any(e => e.Email == id);
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login([Bind("Email,Password")] Teacher teacher)
        {

            var data = await _context.Teacher.Where((x => x.Email == teacher.Email && x.Password == teacher.Password)).FirstOrDefaultAsync<Teacher>();
            ClaimsIdentity identity = null;

            if (data != null)
            {
                if (data.JWT_Token.Equals("0"))
                {
                    ModelState.AddModelError(string.Empty, "Sorry Your not yet approved by the Admin");
                    return View(teacher);
                }
                else if (data.JWT_Token.Equals("Block"))
                {
                    ModelState.AddModelError(string.Empty, "Sorry Your Blocked By The Admin");
                    return View(teacher);
                }

                else if (ValidateToken(data.JWT_Token).Contains("Unable to decode the header"))
                {
                    ModelState.AddModelError(string.Empty, "Sorry Something Went Horror");
                    return View(teacher);
                }
                else if (ValidateToken(data.JWT_Token).Contains("Lifetime validation failed"))
                {
                    ModelState.AddModelError(string.Empty, "Your Deadline is Expired Please Contact with Admin");
                    return View(teacher);
                }
                else if (ValidateToken(data.JWT_Token).Contains("Decode_Error_1000323_Temparing_With_Token"))
                {
                    ModelState.AddModelError(string.Empty, "Decode_Error_1000323_Temparing_With_Token");
                    return View(teacher);
                }
                else
                {

                    HttpContext.Session.SetString("Token_Key", data.JWT_Token);
                    HttpContext.Session.SetString("User_Email", data.Email);

                    await HttpContext.SignOutAsync("Student");
                    await HttpContext.SignOutAsync("Teacher");
                    await HttpContext.SignOutAsync("Admin");

                    identity = new ClaimsIdentity(new[] {
                        new Claim(ClaimTypes.Email,teacher.Email),
                        new Claim(ClaimTypes.Role,"Teacher")


                     }, CookieAuthenticationDefaults.AuthenticationScheme);



                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync("Teacher", principal);



                    return Redirect("~/Teachers/Index/");
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "False Login Attempt");
            }




            return View(teacher);
        }


        public IActionResult Answer_The_Qus()
        {
            return View();
        }

      
        [HttpPost]
        public async Task<IActionResult> Answer_The_Qus(String id, Tutorial tutorial)
        {

            var data = await _context.Course.Where(x => x.ID == Convert.ToInt32(id)).FirstOrDefaultAsync<Course>();
            if (data == null)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                _context.Tutorial.Add(tutorial);
                await _context.SaveChangesAsync();
                ViewBag.Message = "Your Answer is Added"; 
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Something Went Wrong");
            }

            return View(tutorial);
        }

        private  String ValidateToken(string authToken)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var validationParameters = GetValidationParameters();

            SecurityToken validatedToken;
            try
            {
                IPrincipal principal = tokenHandler.ValidateToken(authToken, validationParameters, out validatedToken);
            }
            catch (Exception e)
            {

                return e.ToString()+"Decode_Error_1000323_Temparing_With_Token"; 
            }
            return "Fine";
        }
        private  TokenValidationParameters GetValidationParameters()
        {
            return new TokenValidationParameters()
            {
                ClockSkew = TimeSpan.Zero,
                ValidIssuer = Constent.Issuer,
                ValidAudience = Constent.Audiance,
                IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Constent.Secret)) // The same key as the one that generate the token
            };
        }
    }
}

Online_School_Teacher/Online_School_Teacher/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online School Teacher</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online_School_Teacher</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Add_Course">Add Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Teacher_List">Teacher List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Course_List">Course List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Online_School_Teacher - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   

    @RenderSection("Scripts", required: false)
</body>
</html>

Online_School_Teacher/Online_School_Teacher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online School Teacher</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online_School_Teacher</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Create">Teacher Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Create">Student Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Login"> Teacher Login </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Online_School_Teacher - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>